name: SILENIUM TEST

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  selenium:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager
    - name: Install Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'
    - name: Download Selenium server
      run: |
        wget https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar 
    - name: Install Nodejs
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: | 
       npm install -g selenium-side-runner
       npm install -g chromedriver   
    - name: Install Google-Chrome
      uses: browser-actions/setup-chrome@v1  
    - name: Run Selenium IDE script
      run: | 
        java -jar selenium-server-standalone-3.141.59.jar -browser "browserName=chrome,chromeOptions={args: ['--headless', '--disable-gpu', '--disable-dev-shm-usage']" &
        selenium-side-runner -c "browserName=chrome"  Pre_Mila.side
        
#        java -jar selenium-server-standalone-<version>.jar -Dwebdriver.chrome.driver=<path/to/chromedriver> 
#        -enablePassThrough false -browser "browserName=chrome,chromeOptions={args: ['--headless', '--disable-gpu']}"

